import { useState } from "react";

const CreateBackupIntro = ({ onContinue }) => {
  const [checks, setChecks] = useState([false, false, false]);

  const toggleCheck = (index) => {
    const newChecks = [...checks];
    newChecks[index] = !newChecks[index];
    setChecks(newChecks);
  };

  const allChecked = checks.every((c) => c);

  return (
    <div className="card max-w-3xl w-full mx-auto ">
      <div className="text-center space-y-8 py-8">
        <div className="w-16 h-16 mx-auto rounded-full bg-success/10 flex items-center justify-center">
          <svg
            className="w-8 h-8 text-success"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"
            />
          </svg>
        </div>
        <div>
          <h2 className="text-3xl font-light mb-3">Create wallet backup</h2>
          <p className="text-light-text max-w-xl mx-auto">
            Your wallet backup consists of a list of words generated by your
            Trezor. Write it down accurately and store securely. It's the only
            way to recover your funds.
          </p>
        </div>

        <div className="max-w-2xl mx-auto">
          <p className="text-sm text-light-text mb-6">
            Click to confirm you've carefully read and understood the
            instructions in each box below.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {[
              {
                icon: "M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z",
                text: "I understand that I can use my wallet backup to recover my assets if I lose or damage my Trezor.",
              },
              {
                icon: "M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z M15 13a3 3 0 11-6 0 3 3 0 016 0z",
                text: "I'll never take a picture of my wallet backup or store it anywhere digital.",
              },
              {
                icon: "M19 14l-7 7m0 0l-7-7m7 7V3",
                text: "I'll store my wallet backup securely and never share it with anyone.",
              },
            ].map((item, i) => (
              <button
                key={i}
                onClick={() => toggleCheck(i)}
                className="flex flex-col items-center p-6 bg-glass-bg border border-glass-border rounded-xl hover:bg-white/5 transition min-h-65"
              >
                {/* Icon */}
                <div className="w-10 h-10 rounded-full bg-success/10 flex items-center justify-center mb-4">
                  <svg
                    className="w-5 h-5 text-light-text"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    strokeWidth={2}
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d={item.icon}
                    />
                  </svg>
                </div>

                {/* Text */}
                <p className="text-sm text-light-text text-center leading-relaxed flex-1">
                  {item.text}
                </p>

                {/* Checkbox */}
                <div
                  className={`w-6 h-6 mt-4 rounded border-2 flex items-center justify-center transition ${
                    checks[i] ? "bg-success border-success" : "border-gray-600"
                  }`}
                >
                  {checks[i] && (
                    <svg
                      className="w-4 h-4 text-black"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                      strokeWidth={3}
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                  )}
                </div>
              </button>
            ))}
          </div>
        </div>

        <button
          onClick={onContinue}
          disabled={!allChecked}
          className={`btn-primary mt-8 px-12 py-3 text-base ${
            !allChecked ? "opacity-50 cursor-not-allowed" : ""
          }`}
        >
          Create wallet backup
        </button>
      </div>
    </div>
  );
};

export default CreateBackupIntro;
